amcl:
  ros__parameters:
    use_sim_time: True
    global_frame_id: map1
    odom_frame_id: kris_robot1_odom
    base_frame_id: kris_robot1_base_link
    scan_topic: /kris_robot1/scan    

bt_navigator:
  ros__parameters:
    global_frame: map1
    robot_base_frame: kris_robot1_base_link
    odom_frame_id: kris_robot1_odom
    odom_topic: /kris_robot1/odom    
    navigators: ["navigate_to_pose"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    use_sim_time: True
    odom_topic: /kris_robot1/odom
    odom_frame_id: kris_robot1_odom
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["GoalAlignCritic", "PathAlignCritic", "PreferForwardCritic"]
      # min_vel_x: 0.05
      # max_vel_x: 0.75
      # min_vel_theta: -1.0
      # max_vel_theta: 1.5
      # acc_lim_x: 0.75
      # acc_lim_theta: 2.0
      vx_samples: 30
      vtheta_samples: 40
      GoalAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 1.4
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 6.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        threshold_to_consider: 0.5

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    odom_frame_id: kris_robot1_odom
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.5, 2.5]
    min_velocity: [-0.5, -0.5, -2.5]
    max_accel: [0.3, 0.3, 3.2]
    max_decel: [-0.5, -0.5, -3.2]
    odom_topic: "/kris_robot1/odom"
    odom_frame_id: kris_robot1_odom
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    base_frame_id: "kris_robot1_base_link"
    odom_frame_id: "kris_robot1_odom"
    cmd_vel_in_topic: "/cmd_vel_smoothed"
    cmd_vel_out_topic: "/kris_robot1/cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
    # and robot footprint for "approach" action type.
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 0.5
      simulation_time_step: 0.1
      min_points: 3
      visualize: True
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/kris_robot1/scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    local_frame: kris_robot1_odom
    global_frame: map1
    robot_base_frame: kris_robot1_base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.50
    min_rotational_vel: 0.40
    rotational_acc_lim: 3.2


global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map1
      map_topic: /map1
      robot_base_frame: kris_robot1_base_link
      use_sim_time: True
      robot_radius: 0.08
      resolution: 0.05
      track_unknown_space: false
      rolling_window: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /kris_robot1/scan
          data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.20
      always_send_full_costmap: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: kris_robot1_odom      
      robot_base_frame: kris_robot1_base_link
      use_sim_time: true
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.08
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        publish_obstacle_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_obstacles: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /kris_robot1/scan
          max_obstacle_height: 2.0
          data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.20
      always_send_full_costmap: True
