topics:
  - name: /local_costmap/costmap
    type: nav_msgs/msg/OccupancyGrid
    expected_rate: 10.0
    tolerance: 0.10
  - name: /global_costmap/costmap
    type: "nav_msgs/msg/OccupancyGrid"
    expected_rate: 5.0
    tolerance: 0.10
    window: 20
  - name: /kris_robot1/scan
    type: sensor_msgs/msg/LaserScan
    expected_rate: 5.0
    tolerance: 0.10
  - name: /clock
    type: rosgraph_msgs/msg/Clock
    expected_rate: 20.0
    tolerance: 0.10
  - name: /local_costmap/published_footprint
    type: geometry_msgs/msg/PolygonStamped
    expected_rate: 1.0
    tolerance: 0.10