- gz_topic_name: /model/kris_robot/tf
  gz_type_name: gz.msgs.Pose_V
  ros_topic_name: /tf
  ros_type_name: tf2_msgs/msg/TFMessage
  direction: GZ_TO_ROS

- gz_topic_name: /kris_robot1/cmd_vel
  gz_type_name: gz.msgs.Twist
  ros_topic_name: /kris_robot1/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist

- gz_topic_name: /kris_robot1/odom
  gz_type_name: gz.msgs.Odometry
  ros_topic_name: /kris_robot1/odom
  ros_type_name: nav_msgs/msg/Odometry

- gz_topic_name: /kris_robot1/scan
  gz_type_name: gz.msgs.LaserScan
  ros_topic_name: /kris_robot1/scan
  ros_type_name: sensor_msgs/msg/LaserScan

- gz_topic_name: /clock
  gz_type_name: gz.msgs.Clock
  ros_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  direction: GZ_TO_ROS